<section class="bg-[#222222] py-12 sm:py-16 lg:py-24">
    <div class="container mx-auto px-4 sm:px-6">
        <div class="text-center max-w-4xl mx-auto">
            <h2 class="text-2xl sm:text-3xl lg:text-4xl font-bold text-dark-section-foreground mb-4 sm:mb-6">Let's Launch Your Publishing Journey the Right Way</h2>
            <p class="text-base sm:text-lg text-dark-section-foreground mb-6 sm:mb-8 px-2 sm:px-0">Join thousands of successful publishers who have transformed their passion into profit. Start building your KDP empire today with our proven strategies and expert guidance.</p>
            <div class="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center"><a href="<?= url('/contact') ?>"><button class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 h-10 bg-accent text-accent-foreground hover:bg-accent/90 px-6 sm:px-8 py-3 text-base sm:text-lg w-full sm:w-auto" data-track-checkout="Submit Service Request"><span class="text-sm sm:text-base">Submit a Service Request</span><img src="<?= asset('assets/Arrow-black-AVsc0Ug-.svg') ?>" width="37" height="10" loading="lazy" decoding="async" alt="Arrow" class="ml-2 w-3 h-3 sm:w-4 sm:h-4"></button></a><a href="<?= url('/book-call') ?>"><button class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 bg-secondary text-secondary-foreground hover:bg-secondary/80 h-10 px-4 py-2 w-full sm:w-auto" data-track-checkout="Book Free Call"><span class="text-sm sm:text-base">Book a FREE call</span><img src="<?= icon('call') ?>" alt="Arrow" class="ml-2 w-3 h-3 sm:w-4 sm:h-4"></button></a></div>
        </div>
    </div>
</section>
